/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as AnnotationPromptRouteImport } from './routes/annotation-prompt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsSeqtrainerRouteImport } from './routes/tools.seqtrainer'
import { Route as ToolsSbolValidatorRouteImport } from './routes/tools.sbol-validator'
import { Route as ToolsSbolCanvasRouteImport } from './routes/tools.sbol-canvas'
import { Route as ToolsBenchlabRouteImport } from './routes/tools.benchlab'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotationPromptRoute = AnnotationPromptRouteImport.update({
  id: '/annotation-prompt',
  path: '/annotation-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSeqtrainerRoute = ToolsSeqtrainerRouteImport.update({
  id: '/tools/seqtrainer',
  path: '/tools/seqtrainer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSbolValidatorRoute = ToolsSbolValidatorRouteImport.update({
  id: '/tools/sbol-validator',
  path: '/tools/sbol-validator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSbolCanvasRoute = ToolsSbolCanvasRouteImport.update({
  id: '/tools/sbol-canvas',
  path: '/tools/sbol-canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBenchlabRoute = ToolsBenchlabRouteImport.update({
  id: '/tools/benchlab',
  path: '/tools/benchlab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annotation-prompt': typeof AnnotationPromptRoute
  '/glossary': typeof GlossaryRoute
  '/workflow': typeof WorkflowRoute
  '/tools/benchlab': typeof ToolsBenchlabRoute
  '/tools/sbol-canvas': typeof ToolsSbolCanvasRoute
  '/tools/sbol-validator': typeof ToolsSbolValidatorRoute
  '/tools/seqtrainer': typeof ToolsSeqtrainerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annotation-prompt': typeof AnnotationPromptRoute
  '/glossary': typeof GlossaryRoute
  '/workflow': typeof WorkflowRoute
  '/tools/benchlab': typeof ToolsBenchlabRoute
  '/tools/sbol-canvas': typeof ToolsSbolCanvasRoute
  '/tools/sbol-validator': typeof ToolsSbolValidatorRoute
  '/tools/seqtrainer': typeof ToolsSeqtrainerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annotation-prompt': typeof AnnotationPromptRoute
  '/glossary': typeof GlossaryRoute
  '/workflow': typeof WorkflowRoute
  '/tools/benchlab': typeof ToolsBenchlabRoute
  '/tools/sbol-canvas': typeof ToolsSbolCanvasRoute
  '/tools/sbol-validator': typeof ToolsSbolValidatorRoute
  '/tools/seqtrainer': typeof ToolsSeqtrainerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annotation-prompt'
    | '/glossary'
    | '/workflow'
    | '/tools/benchlab'
    | '/tools/sbol-canvas'
    | '/tools/sbol-validator'
    | '/tools/seqtrainer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annotation-prompt'
    | '/glossary'
    | '/workflow'
    | '/tools/benchlab'
    | '/tools/sbol-canvas'
    | '/tools/sbol-validator'
    | '/tools/seqtrainer'
  id:
    | '__root__'
    | '/'
    | '/annotation-prompt'
    | '/glossary'
    | '/workflow'
    | '/tools/benchlab'
    | '/tools/sbol-canvas'
    | '/tools/sbol-validator'
    | '/tools/seqtrainer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnotationPromptRoute: typeof AnnotationPromptRoute
  GlossaryRoute: typeof GlossaryRoute
  WorkflowRoute: typeof WorkflowRoute
  ToolsBenchlabRoute: typeof ToolsBenchlabRoute
  ToolsSbolCanvasRoute: typeof ToolsSbolCanvasRoute
  ToolsSbolValidatorRoute: typeof ToolsSbolValidatorRoute
  ToolsSeqtrainerRoute: typeof ToolsSeqtrainerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotation-prompt': {
      id: '/annotation-prompt'
      path: '/annotation-prompt'
      fullPath: '/annotation-prompt'
      preLoaderRoute: typeof AnnotationPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/seqtrainer': {
      id: '/tools/seqtrainer'
      path: '/tools/seqtrainer'
      fullPath: '/tools/seqtrainer'
      preLoaderRoute: typeof ToolsSeqtrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/sbol-validator': {
      id: '/tools/sbol-validator'
      path: '/tools/sbol-validator'
      fullPath: '/tools/sbol-validator'
      preLoaderRoute: typeof ToolsSbolValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/sbol-canvas': {
      id: '/tools/sbol-canvas'
      path: '/tools/sbol-canvas'
      fullPath: '/tools/sbol-canvas'
      preLoaderRoute: typeof ToolsSbolCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/benchlab': {
      id: '/tools/benchlab'
      path: '/tools/benchlab'
      fullPath: '/tools/benchlab'
      preLoaderRoute: typeof ToolsBenchlabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnotationPromptRoute: AnnotationPromptRoute,
  GlossaryRoute: GlossaryRoute,
  WorkflowRoute: WorkflowRoute,
  ToolsBenchlabRoute: ToolsBenchlabRoute,
  ToolsSbolCanvasRoute: ToolsSbolCanvasRoute,
  ToolsSbolValidatorRoute: ToolsSbolValidatorRoute,
  ToolsSeqtrainerRoute: ToolsSeqtrainerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
